# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "items", :force => true do |t|
    t.column "create_date",     :datetime,                              :null => false
    t.column "number",          :integer,  :limit => 5, :default => 0,  :null => false
    t.column "act_type",        :string,   :limit => 5, :default => "", :null => false
    t.column "item_desc",       :text,                  :default => "", :null => false
    t.column "value_when_done", :string
    t.column "where_to_do",     :string
    t.column "short_task_name", :string
    t.column "swiss_cheese",    :string
    t.column "out_indicator",   :boolean
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer, :limit => 10, :default => 0,  :null => false
    t.column "taggable_id",   :integer, :limit => 10, :default => 0,  :null => false
    t.column "taggable_type", :string,                :default => "", :null => false
  end

  create_table "tags", :force => true do |t|
    t.column "name",       :string,   :default => "", :null => false
    t.column "created_at", :datetime,                 :null => false
    t.column "updated_at", :datetime,                 :null => false
  end

  create_table "users", :force => true do |t|
    t.column "login",    :string, :limit => 80
    t.column "password", :string, :limit => 40
  end

end
